name: "Tests"
on: 
  - push
  - pull_request
jobs:   
  type-checker:
    name: Type checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          args: --shepherd
          
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - version: "8.1"
            phpunit: "10"
          - version: "8.2"
            phpunit: "10"
          - version: "8.3"
            phpunit: "11"
          - version: "8.4"
            phpunit: "12"
    name: "Unit tests: PHP ${{ matrix.php.version }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php.version }}"
      # Install dependencies and handle caching in one go.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Unit tests
        uses: php-actions/phpunit@v4
        with:
          version: "${{ matrix.php.phpunit }}"
          php_version: "${{ matrix.php.version }}"

  rector:
    runs-on: ubuntu-latest
    name: Rector
    
    steps:
      - uses: actions/checkout@v5
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          php_version: "8.4"
      - name: Check compatibility
        run: composer rector
